development:
  :key: 'xxx' 
  :password: 'xxx'
  :account_number: 'xxx'
  :meter: 'xxx' 
  :mode: 'test' 
  
production:  
  :key: 'xxx' 
  :password: 'xxx'
  :account_number: 'xxx'
  :meter: 'xxx' 
  :mode: 'production'